---
version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    reviewers:
      - CandiedCode
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps-dev):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    reviewers:
      - CandiedCode
    commit-message:
      prefix: "chore(ci):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
